[package]
name = "literature-library"
version = "0.8.1"
edition = "2021"

[lib]
name = "literature_library_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lopdf = "0.34"
pdf-extract = "0.8"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
sha1_smol = "1"
regex = "1"
walkdir = "2"
opener = "0.7"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-dialog = "2.6.0"
reqwest = { version = "0.12", features = ["json", "blocking"] }
futures = "0.3"

[profile.release]
strip = true
lto = true
codegen-units = 1
